# Generated by Django 4.1 on 2022-08-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total',
        ),
    ]
