# Generated by Django 4.1 on 2022-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_sales_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(related_name='prdcts', through='crm.Products_sale', to='crm.products'),
        ),
    ]
